"""empty message

Revision ID: ccd8918451c5
Revises: 23c1957587b9
Create Date: 2024-08-23 16:43:05.433329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccd8918451c5'
down_revision = '23c1957587b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skin_color', sa.String(length=30), nullable=True))
        batch_op.drop_column('planet')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.drop_column('skin_color')

    # ### end Alembic commands ###
